version: 0.2

phases:
  pre_build:
   commands:
       - echo "creating test1 folder"
       - mkdir -p ./test1/
  build:
    commands:
        - echo "Copying the file"
        - cp index.html ./test1/
artifacts:
   files:
      - test1/**/*
      - appspec.yml